spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: Mospwn13295X
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

